name: Build, Test and Publish NuGet Package

on:
  workflow_dispatch:     # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Build with dotnet
        run: dotnet build ./src/KTrie.sln --configuration Release

      - name: Test
        run: dotnet test ./src/KTrie.sln
        
  pack:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Extract version from tag
        id: extract_version
        run: |
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          
      - name: Pack NuGet package
        run: dotnet pack ./src/KTrie/KTrie.csproj --configuration Release -p:PackageVersion=${{ env.VERSION }} -o package

      - name: Upload NuGet package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: NuGetPackage
          path: package/*.nupkg

      - name: Push to NuGet
        run: dotnet nuget push "./package/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json